### ISSUE TITLE
Great effort

### ISSUE THREAD

**Issue by tommygebru** [PizzaGymDonut/ColmarAcademy#1]
Great impression on your last submittable project Matthew, I can see that your codebase is well formatted with indentation and commenting, I can navigate your project quickly 🙌. Your work clearly represents the required outcome for this assignment!

Your css and some document files are missing! Please change your file paths with the following:
```
/Users/matthewterrell/Desktop/projects/ColmarAcademy/css/style.css`
```
should be 

```
css/style.css
```

**Comment by tommygebru** [comment]
Also as you begin to use local file paths, make sure to become familiar with relative vs absolute file paths
**Relative file paths,** will secure the project assets and make them viewable anywhere 

**Absolute file paths,** will require that a specific domain name or url to access and view the documents

You can review these concepts further here 

https://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/

**Comment by PizzaGymDonut** [comment]
Thanks Tommy, the links should now be up to date. On my laptop the CSS doesn't display unless the full file path is there - I must have forgot to change these.
