### ISSUE TITLE
NOTES

### ISSUE THREAD

**Issue by tommygebru** [PizzaGymDonut/ColmarAcademy#7]
_NOTE: Always conduct a peer-review with your peers in Slack, this will improve performance and ability to problem solve!_ 💯

Your project contains little to no errors Matthew, I went ahead and reviewed your work for best practices and general areas of improvement 😃

**Comment by tommygebru** [comment]
Make sure to include the right poster file, include the right video file, add controls attribute to access and play the video, and as always make sure your spelling and syntax is correct! 

```
<video poster="resources/images/thesis-now-and-then.jpg" controls>
 <source src="resources/videos/thesis.mp4" type="video/mp4">
</video>
```

**Comment by PizzaGymDonut** [comment]
Thanks, this has now been updated.
